version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - server/.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - client/.env
volumes:
  mongo-data: